support for updating a message, close dm chat, leave channel
noobot/SlackConnector pull request #46
Opened 2017-04-24 17:50 UTC by AnatoliiAPFM

(Simon, please let me know if any comments whatsoever and if need me to change/delete add anything)

* added support for message update (chat.update)
* added support for im.close and challens.leave (though they didn't seem to work for bots, perhaps slack will fix that in the future)
* added 'needed' attribute to StandardResponse for visibility of a missing credentials
* added UpdatedMessage (attr=message) attribute to ChatMessage event to enable tracking of updated messages. This allows to respond/handle messages resulting from updates to misspelled handlers once user fixes them via message edit feature.

2017-04-24 22:57 UTC, AnatoliiAPFM commented
looks that the test requires a config.json, what's the practice of testing without this file being in github? it could be saved as an appveyor build parameter, and possibly could be made viewable only by the owner...

2017-05-07 00:15 UTC, Workshop2 commented
Hi @AnatoliiAPFM,

Looks like this PR broke the build - can you look at fixing it so I can review the PR?

Thanks,
Simon

2017-05-07 00:34 UTC, Workshop2 commented
@AnatoliiAPFM regarding the `config.js`, just take a copy of the `config.default.js` and fill it with your own info for testing. This file is git ignored so the keys are not leaked but can still be tested locally.

2017-05-08 20:54 UTC, AnatoliiAPFM commented on src/SlackConnector/Connections/Clients/Chat/FlurlChatClient.cs
> +        internal const string POST_MESSAGE_PATH = "/api/chat.postMessage";
sorry about the rename, when I added "chat.update" it seemed that would be nice to have the variables coincide with underlying path name as well and renamed send message to post message...

2017-05-08 21:01 UTC, AnatoliiAPFM commented
@Workshop2, Simon, 
it's looking OK now, let me know if need any other changes.
-Anatolii

2017-05-08 21:56 UTC, Workshop2 approved these changes

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/Connections/Clients/Channel/FlurlChannelClient.cs
> +        public async Task CloseDirectMessageChannel(string slackKey, string channel)
Can you write some tests against these new methods

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/Connections/Clients/Chat/FlurlChatClient.cs
> +            return response.Ts;
Instead of returning a string, can you return a model? It currently isn't very intuitive

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/Connections/Clients/Chat/IChatClient.cs
> +        ///
Missing a summary

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/Connections/Clients/ResponseVerifier.cs
> +                string neededMsg = response.Needed!=null?  $", needed:'{response.Needed}'" : string.Empty;
Needs formatting, also what is it doing?

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/Connections/Responses/JoinChannelResponse.cs
> +        public new Channel Channel { get; set; }
Not sure why this is here? If the base has a channel then it isn't needed here

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/Connections/Responses/StandardResponse.cs
> +        public string Needed { get; set; }
Is this needed?

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/SlackConnection.cs
> +            if (inboundMessage == null || inboundMessage.MessageType==MessageType.Unknown)
This isn't required, it will just fall through the switch

2017-05-08 21:56 UTC, Workshop2 commented on src/SlackConnector/SlackConnection.cs
> +        public async Task CloseDirectMessageChannel(string channel)
Can you add tests against these new methods. Also, spacing issue with method above

2017-05-08 21:57 UTC, Workshop2 requested changes
See feedback above

2017-05-09 18:59 UTC, AnatoliiAPFM commented
sounds good I will address these in a couple of days when I have spare time.

2017-08-19 16:51 UTC, closed without merging