Reaction handling
noobot/SlackConnector pull request #64
Opened 2017-10-07 19:45 UTC by loredous

Added handling of Reaction messages. Provides text value of reaction, user that posted the reaction, and timestamp of the item being reacted to.

2017-10-13 10:36 UTC, Workshop2 requested changes
Thanks for helping out. You are missing unit tests against the new logic and see my comments about the JSON parsing.

2017-10-13 10:36 UTC, Workshop2 commented on src/SlackConnector/Connections/Sockets/Messages/Inbound/MessageInterpreter.cs
> +                message.RawData = json;
This is handled in the method that calls this

2017-10-13 10:36 UTC, Workshop2 commented on src/SlackConnector/Connections/Sockets/Messages/Inbound/MessageInterpreter.cs
> +            var message = JsonConvert.DeserializeObject<ReactionMessage>(json);
Why are you parsing this object and then overriding the properties later? Can't this just be done in the de-serialise?

2017-10-13 10:36 UTC, Workshop2 commented on src/SlackConnector/Connections/Sockets/Messages/Inbound/MessageInterpreter.cs
> +                    case MessageType.Reaction_Added:
Missing tests

2017-10-13 10:36 UTC, Workshop2 commented on src/SlackConnector/SlackConnection.cs
> +                case MessageType.Reaction_Added: return HandleReaction((ReactionMessage)inboundMessage);
Missing tests

2017-10-21 19:28 UTC, loredous commented
Added requested changes plus a few enhancements to deal with all current Reaction message types. Added unit tests for all new functionality.

2017-10-25 20:51 UTC, closed without merging