F/new channel methods
noobot/SlackConnector pull request #65
Opened 2017-10-15 20:52 UTC by AshleyPoole

This PR adds the ability to:
- Create channel
- Join channel
- Set channel purpose
- Set channel topic
- Archive channel

All new methods have accompanying tests using the format setup already in this repo.

This PR implements the feature request in issue (feature request) #11.

2017-10-15 20:53 UTC, AshleyPoole commented
@Workshop2 ready for your review.

2017-10-16 06:31 UTC, Workshop2 requested changes
Wow, amazing work. A couple of bits of feedback.

2017-10-16 06:31 UTC, Workshop2 commented on src/SlackConnector/ISlackConnection.cs
> +        /// Creates a channel.
Wrong XML comment

2017-10-16 06:31 UTC, Workshop2 commented on src/SlackConnector/ISlackConnection.cs
> +        /// Joins a channel.
And again

2017-10-16 06:31 UTC, Workshop2 commented on tests/SlackConnector.Tests.Unit/Connections/Clients/Flurl/FlurlChannelClientTests.cs
> +            try
Should let exceptions bubble up and be caught by the test harness

2017-10-16 07:17 UTC, AshleyPoole commented
@Workshop2 corrections made.

2017-10-16 19:58 UTC, merged

2017-10-16 19:58 UTC, Workshop2 commented
Thanks @ashleypoole

Fantastic work

2017-10-16 21:33 UTC, AshleyPoole commented
Are you able to publish the nuget package for the latest version @Workshop2? I've checked nuget just but it's showing the old previous version.

2017-10-16 21:47 UTC, Workshop2 commented
Done